global im jm kb imm1 imm2 jmm1 jmm2 kbm1 kbm2 kl1 kl2 z zz dz dzz z_3d zz_3d dz_3d dzz_3d ...
    dx dy art aru arv  fsm dum dvm dx_3d dy_3d art_3d aru_3d arv_3d fsm_3d dum_3d dvm_3d;

global small pi netcdf_file iproblem mode nadv nitera sw nread dte isplit days prtd1 prtd2 swtch iskp jskp ...
     lramp rhoref tbias sbias grav kappa z0b cbcmin cbcmax horcon tprni umol hmax vmaxl slmax ntp nbct nbcs ...
     ispadv smoth alpha dti dte2 dti2 iend iprint iswtch ispi isp2i;
global OP gs gridtype cor cor_3d h h_3d aam_init;