[east_c,north_c,east_e,north_e,east_u,north_u,east_v,north_v,tb,sb,tclim, ...
 sclim,ub,uab,elb,etb,dt,aam2d,rho,rmean,rfe,rfw,rfn,rfs,uabw,uabe,ele,   ...
 elw,tbe,tbw,sbe,sbw,tbn,tbs,sbn,sbs,vb,rot,els,eln,vabs,vabn,ubw,ube,vbs,...
 vbn,ssurf,tsurf,wusurf,wvsurf] = read_nc_file;