! ***********************************************************************
! 
!     Common blocks for pom08.f
! 
! ***********************************************************************
! 
!     source_c should agree with source in pom08.f.
! 
      character*40 source_c
      parameter(source_c='pom08  2008-04-18')
! 
! ***********************************************************************
! 
!     Array sizes:
! 
      integer                                                             &
     &  im             ,imm1           ,imm2           ,jm             ,  &
     &  jmm1           ,jmm2           ,kb             ,kbm1           ,  &
     &  kbm2
! 
! ***********************************************************************
! 
!     Set size of problem here:
! 
!     parameter
! -- file2ic (iproblem=3)
!    $ (im=41          ,jm=61          ,kb=16)
! -- seamount (iproblem=1)
!    $ (im=65          ,jm=49          ,kb=21)
! ---- from parameter file generated by runpom2k ----
      include 'grid'
! 
! ***********************************************************************
! 
      parameter                                                           &
     & (imm1=im-1      ,imm2=im-2      ,jmm1=jm-1      ,jmm2=jm-2      ,  &
     &  kbm1=kb-1      ,kbm2=kb-2      )
! 
! -----------------------------------------------------------------------
! 
!     Scalars:
! 
      real                                                                &
     &  alpha          ,dte            ,dti            ,dti2           ,  &
     &  grav           ,hmax           ,kappa          ,pi             ,  &
     &  ramp           ,rfe            ,rfn            ,rfs            ,  &
     &  rfw            ,rhoref         ,sbias          ,slmax          ,  &
     &  small          ,tbias          ,time           ,tprni          ,  &
     &  umol           ,vmaxl
! 
      integer                                                             &
     &  iint           ,iprint         ,iskp           ,jskp           ,  &
     &  kl1            ,kl2            ,mode           ,ntp
! 
      common/blkcon/                                                      &
     &  alpha          ,dte            ,dti            ,dti2           ,  &
     &  grav           ,hmax           ,kappa          ,pi             ,  &
     &  ramp           ,rfe            ,rfn            ,rfs            ,  &
     &  rfw            ,rhoref         ,sbias          ,slmax          ,  &
     &  small          ,tbias          ,time           ,tprni          ,  &
     &  umol           ,vmaxl          ,                                  &
     &  iint           ,iprint         ,iskp           ,jskp           ,  &
     &  kl1            ,kl2            ,mode           ,ntp
! 
! -----------------------------------------------------------------------
! 
!     1-D arrays:
! 
      real                                                                &
     &  dz             ,dzz            ,z              ,zz
! 
      common/blk1d/                                                       &
     &  dz(kb)         ,dzz(kb)        ,z(kb)          ,zz(kb)
! 
! -----------------------------------------------------------------------
! 
!     2-D arrays:
! 
      real                                                                &
     &  aam2d          ,advua          ,advva          ,adx2d          ,  &
     &  ady2d          ,art            ,aru            ,arv            ,  &
     &  cbc            ,cor            ,d              ,drx2d          ,  &
     &  dry2d          ,dt             ,dum            ,dvm            ,  &
     &  dx             ,dy             ,east_c         ,east_e         ,  &
     &  east_u         ,east_v         ,e_atmos        ,egb            ,  &
     &  egf            ,el             ,elb            ,elf            ,  &
     &  et             ,etb            ,etf            ,fluxua         ,  &
     &  fluxva         ,fsm            ,h              ,north_c        ,  &
     &  north_e        ,north_u        ,north_v        ,psi            ,  &
     &  rot            ,ssurf          ,swrad          ,vfluxb         ,  &
     &  tps            ,tsurf          ,ua             ,vfluxf         ,  &
     &  uab            ,uaf            ,utb            ,utf            ,  &
     &  va             ,vab            ,vaf            ,                  &
     &  vtb            ,vtf            ,wssurf         ,wtsurf         ,  &
     &  wubot          ,wusurf         ,wvbot          ,wvsurf
! 
      common/blk2d/                                                       &
     &  aam2d(im,jm)   ,advua(im,jm)   ,advva(im,jm)   ,adx2d(im,jm)   ,  &
     &  ady2d(im,jm)   ,art(im,jm)     ,aru(im,jm)     ,arv(im,jm)     ,  &
     &  cbc(im,jm)     ,cor(im,jm)     ,d(im,jm)       ,drx2d(im,jm)   ,  &
     &  dry2d(im,jm)   ,dt(im,jm)      ,dum(im,jm)     ,dvm(im,jm)     ,  &
     &  dx(im,jm)      ,dy(im,jm)      ,east_c(im,jm)  ,east_e(im,jm)  ,  &
     &  east_u(im,jm)  ,east_v(im,jm)  ,e_atmos(im,jm) ,egb(im,jm)     ,  &
     &  egf(im,jm)     ,el(im,jm)      ,elb(im,jm)     ,elf(im,jm)     ,  &
     &  et(im,jm)      ,etb(im,jm)     ,etf(im,jm)     ,fluxua(im,jm)  ,  &
     &  fluxva(im,jm)  ,fsm(im,jm)     ,h(im,jm)       ,north_c(im,jm) ,  &
     &  north_e(im,jm) ,north_u(im,jm) ,north_v(im,jm) ,psi(im,jm)     ,  &
     &  rot(im,jm)     ,ssurf(im,jm)   ,swrad(im,jm)   ,vfluxb(im,jm)  ,  &
     &  tps(im,jm)     ,tsurf(im,jm)   ,ua(im,jm)      ,vfluxf(im,jm)  ,  &
     &  uab(im,jm)     ,uaf(im,jm)     ,utb(im,jm)     ,utf(im,jm)     ,  &
     &  va(im,jm)      ,vab(im,jm)     ,vaf(im,jm)     ,                  &
     &  vtb(im,jm)     ,vtf(im,jm)     ,wssurf(im,jm)  ,wtsurf(im,jm)  ,  &
     &  wubot(im,jm)   ,wusurf(im,jm)  ,wvbot(im,jm)   ,wvsurf(im,jm)
! 
! -----------------------------------------------------------------------
! 
!     3-D arrays:
! 
      real                                                                &
     &  aam            ,advx           ,advy           ,a              ,  &
     &  c              ,drhox          ,drhoy          ,dtef           ,  &
     &  ee             ,gg             ,kh             ,km             ,  &
     &  kq             ,l              ,q2b            ,q2             ,  &
     &  q2lb           ,q2l            ,rho            ,rmean          ,  &
     &  sb             ,sclim          ,s              ,tb             ,  &
     &  tclim          ,t              ,ub             ,uf             ,  &
     &  u              ,vb             ,vf             ,v              ,  &
     &  w              ,zflux
! 
      common/blk3d/                                                       &
     &  aam(im,jm,kb)  ,advx(im,jm,kb) ,advy(im,jm,kb) ,a(im,jm,kb)    ,  &
     &  c(im,jm,kb)    ,drhox(im,jm,kb),drhoy(im,jm,kb),dtef(im,jm,kb) ,  &
     &  ee(im,jm,kb)   ,gg(im,jm,kb)   ,kh(im,jm,kb)   ,km(im,jm,kb)   ,  &
     &  kq(im,jm,kb)   ,l(im,jm,kb)    ,q2b(im,jm,kb)  ,q2(im,jm,kb)   ,  &
     &  q2lb(im,jm,kb) ,q2l(im,jm,kb)  ,rho(im,jm,kb)  ,rmean(im,jm,kb),  &
     &  sb(im,jm,kb)   ,sclim(im,jm,kb),s(im,jm,kb)    ,tb(im,jm,kb)   ,  &
     &  tclim(im,jm,kb),t(im,jm,kb)    ,ub(im,jm,kb)   ,uf(im,jm,kb)   ,  &
     &  u(im,jm,kb)    ,vb(im,jm,kb)   ,vf(im,jm,kb)   ,v(im,jm,kb)    ,  &
     &  w(im,jm,kb)    ,zflux(im,jm,kb)
! 
! -----------------------------------------------------------------------
! 
!     1 and 2-D boundary value arrays:
! 
      real                                                                &
     &  ele            ,eln            ,els            ,elw            ,  &
     &  sbe            ,sbn            ,sbs            ,sbw            ,  &
     &  tbe            ,tbn            ,tbs            ,tbw            ,  &
     &  uabe           ,uabw           ,ube            ,ubw            ,  &
     &  vabn           ,vabs           ,vbn            ,vbs
! 
      common/bdry/                                                        &
     &  ele(jm)        ,eln(im)        ,els(im)        ,elw(jm)        ,  &
     &  sbe(jm,kb)     ,sbn(im,kb)     ,sbs(im,kb)     ,sbw(jm,kb)     ,  &
     &  tbe(jm,kb)     ,tbn(im,kb)     ,tbs(im,kb)     ,tbw(jm,kb)     ,  &
     &  uabe(jm)       ,uabw(jm)       ,ube(jm,kb)     ,ubw(jm,kb)     ,  &
     &  vabn(im)       ,vabs(im)       ,vbn(im,kb)     ,vbs(im,kb)
! 
! -----------------------------------------------------------------------
! 
!     Character variables:
! 
      character*26                                                        &
     &  time_start
! 
      character*40                                                        &
     &  source,title
! 
      common/blkchar/                                                     &
     &  time_start     ,source         ,title
! 
!                                                                      !
! ----------------------------------------------------------------------!
! lyo:!wad:begins:                                                      !
! ----------------------------------------------------------------------!
! ----------------------------------------------------------------------!
!   Common variables associated with WAD                               !
! ----------------------------------------------------------------------!
! ----------------------------------------------------------------------!
      integer nwad
! 
      real                                                                &
     &    alph0,hhi0,tidamp,hco,                                          &
     &    zsh,                                                            &
     &    hmin,hc,hhi,                                                    &
     &    dtrat,cwetrlx1,cwetrlx2 ! Relax params. for when river water
                                  ! is discharged onto dry cells
! 
      common/blkconwad/                                                   &
     &  alph0          ,hhi0           ,tidamp         ,hco            ,  &
     &  zsh            ,hmin           ,hc             ,hhi            ,  &
     &  dtrat          ,cwetrlx1       ,cwetrlx2       ,nwad
! 
      real                                                                &
     &  wriv           ,dwet           ,wetmask        ,wmarsh         ,  &
     &  ddf            ,dd0            ,ddb            ,ssurfwet       ,  &
     &  hkeep
! 
      common/blk2dwad/    ! ALL but wriv are used in main prog. only:      &
     &    wriv(im,jm),    ! used in main & subr.advt!not implemented yet   &
     &    dwet(im,jm),wetmask(im,jm),wmarsh(im,jm),                       &
     &    ddf(IM,JM),dd0(IM,JM),ddb(IM,JM),                               &
     &    hkeep(im,jm),ssurfwet(im,jm) ! used for river specifications
! 
      real                                                                &
     &  pdens
! 
      common/blk3dwad/                                                    &
     &    pdens(im,jm,kb)              ! used in dens & profq
      integer wadmodify
      common/blkwm/wadmodify
!                                                                      !
! lyo:!wad:ends:                                                        !
! ----------------------------------------------------------------------!
!                                                                      !
! -----------------------------------------------------------------------
! 
!     End of common blocks
! 
! -----------------------------------------------------------------------
